spring:
  datasource:
    url: jdbc:h2:file:./database
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
server:
  port: 8443
  ssl:
    key-store-password: abc123
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-alias: tomcat
